<?php

/*
Link Vault's array of supported mime-types.
*/
return array(
	"asf" =>     "video/x-ms-asf",
	"avi" =>     "video/x-msvideo",
	"bin" =>     "application/octet-stream",
	"bmp" =>     "image/bmp",
	"cbr" =>     "application/x-rar-compressed",
	"cbt" =>     "application/x-tar",
	"cbz" =>     "application/zip",
	"cgi" =>     "magnus-internal/cgi",
	"css" =>     "text/css",
	"dcr" =>     "application/x-director",
	"dxr" =>     "application/x-director",
	"dll" =>     "application/octet-stream",
	"doc" =>     "application/msword",
	'docx' =>    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"epub" =>    "application/epub+zip",
	"exe" =>     "application/octet-stream",
	"gif" =>     "image/gif",
	"gtar" =>    "application/x-gtar",
	"gz" =>      "application/x-gzip",
	"htm" =>     "text/html",
	"html" =>    "text/html",
	"iso" =>     "application/octet-stream",
	"jar" =>     "application/java-archive",
	"java" =>    "text/x-java-source",
	"jnlp" =>    "application/x-java-jnlp-file",
	"js" =>      "application/x-javascript",
	"jpg" =>     "image/jpg",
	"jpe" =>     "image/jpg",
	"jpeg" =>    "image/jpg",
	"lzh" =>     "application/octet-stream",
	"mdb" =>     "application/mdb",
	"mid" =>     "audio/x-midi",
	"midi" =>    "audio/x-midi",
	"mov" =>     "video/quicktime",
	"mp2" =>     "audio/x-mpeg",
	"mp3" =>     "audio/mpeg",
	"mp4" =>     "video/mp4",
	"mpg" =>     "video/mpeg",
	"mpe" =>     "video/mpeg",
	"mpeg" =>    "video/mpeg",
	"pdf" =>     "application/pdf",
	"php" =>     "application/x-httpd-php",
	"png" =>     "image/png",
	"ppt" =>     "application/mspowerpoint",
	"pptx" =>    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	"qt" =>      "video/quicktime",
	"qti" =>     "image/x-quicktime",
	"rar" =>     "application/x-rar-compressed",
	"ra" =>      "audio/x-pn-realaudio",
	"rm" =>      "audio/x-pn-realaudio",
	"ram" =>     "audio/x-pn-realaudio",
	"rtf" =>     "application/rtf",
	"swa" =>     "application/x-director",
	"swf" =>     "application/x-shockwave-flash",
	"tar" =>     "application/x-tar",
	"tgz" =>     "application/gzip",
	"tif" =>     "image/tiff",
	"tiff" =>    "image/tiff",
	"torrent" => "application/x-bittorrent",
	"txt" =>     "text/plain",
	"wav" =>     "audio/wav",
	"wma" =>     "audio/x-ms-wma",
	"wmv" =>     "video/x-ms-wmv",
	"xls" =>     "application/vnd.ms-excel",
	"xlsx" =>    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"xml" =>     "application/xml",
	"7z" =>      "application/x-compress",
	"zip" =>     "application/zip"
);
